// Generated by https://quicktype.io

export interface Block {
	blockName: string;
	attrs: BlockAttrs[];
	innerBlocks: Block[];
	innerHTML: string;
	innerContent: Array<string | null>;
}

export type BlockAttrs = Record<string, any>

declare module 'vue' {
	export interface GlobalComponents {
		'BlockRender': typeof import("../render.vue")['default'],
	}
}